FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Laplata2025
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=3000
ENV WEBHOOK_URL=https://n8n-la-plata.onrender.com
ENV GENERIC_TIMEZONE=America/Argentina/Buenos_Aires

EXPOSE 3000
